services:
  activemq-artemis:
    image: apache/activemq-artemis:latest
    container_name: activemq-artemis-aiintegrations
    ports:
      - "6613:61616" # Puerto JMS
      - "65533:8161" # Consola web
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin

networks:
  default:
    name: shared-network
    external: true