services:
  activemq-artemis:
    image: apache/activemq-artemis:latest
    container_name: activemq-artemis
    ports:
      - "61616:61616"  # Puerto JMS
      - "8161:8161"    # Consola web
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin