server:
  port: 8087
spring:
  application:
    name: mic-aiintegrations
  jms:
    broker-url: ${SPRING_JMS_BROKER_URL}
    user: ${SPRING_JMS_USER}
    password: ${SPRING_JMS_PASSWORD}
producer:
  event:
    host: localhost
    port: 6613
    user: admin
    password: admin
  topic:
    name: aiintegrations.processed-asset
consumer:
  event:
    host: localhost
    port: 6612
    user: admin
    password: admin
  topic:
    name: job-offer.candidate
  subscription:
    name: aiintegrations
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=antharos;AccountKey=IOxTIv6pzk3gZrAQzZ9Sq0w+nGhgCsfcLSNrQfTrT7eMwluoLR4r+9H4qrvFKjAYPr3I47OyKQZ1+AStLH6m8A==;EndpointSuffix=core.windows.net
    container-name: cvs