server:
  port: 8080
spring:
  application:
    name: mic-aiintegrations
  jms:
    broker-url: ${SPRING_JMS_BROKER_URL}
    user: ${SPRING_JMS_USER}
    password: ${SPRING_JMS_PASSWORD}
producer:
  event:
    host: ${PRODUCER_ARTEMIS_HOST:localhost}
    port: ${PRODUCER_ARTEMIS_PORT:61616}
    user: ${PRODUCER_ARTEMIS_USER:admin}
    password: ${PRODUCER_ARTEMIS_PASSWORD:admin}
  topic:
    name: ${PRODUCER_TOPIC_NAME:test-topic}
consumer:
  event:  
    host: ${CONSUMER_ARTEMIS_HOST:localhost}
    port: ${CONSUMER_ARTEMIS_PORT:61616}
    user: ${CONSUMER_ARTEMIS_USER:admin}
    password: ${CONSUMER_ARTEMIS_PASSWORD:admin}
  topic:
    name: ${CONSUMER_TOPIC_NAME:test-topic}
  subscription:
    name: ${CONSUMER_SUBSCRIPTION_NAME:my-subscription}