ai-integrations:
  event:
    host: antharos.servicebus.windows.net
    port: 6616
    user: RootManageSharedAccessKey
  topic:
    name: aiintegrations
job-offer:
  event:
    host: antharos.servicebus.windows.net
    port: 6616
    user: RootManageSharedAccessKey
  topic:
    name: joboffer
  subscription:
    name: aiintegrations