producer:
  event:
    connection-string: ${EVENT_CONNECTION_STRING}
  topic:
    name: aiintegrations
consumer:
  event:
    connection-string: ${EVENT_CONNECTION_STRING}
  topic:
    name: joboffer
  subscription:
    name: aiintegrations